name: Component Visual Regression Test
on:
  pull_request:
    branches:
      - "**"
jobs:
  component_visual_regression:
    name: component_visual_regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Application
        run: pnpm build

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Run Chromatic for Component Visual Regression
        uses: chromaui/action@latest
        with:
          projectToken: "chpt_7c5b9bb84eaa5f7"
