name: E2E Visual Regression Test
on:
  pull_request:
    branches:
      - main

jobs:
  e2e_visual_regression:
    name: e2e_visual_regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full git history for Chromatic

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Application
        run: pnpm build

      - name: Start Application
        run: pnpm start &
        env:
          PORT: 3000

      - name: Wait for Application to Start
        run: |
          while ! nc -z localhost 3000; do   
            sleep 1
          done

      # Run Cypress tests
      - name: Run Cypress Tests
        run: pnpx cypress run --spec cypress/e2e/test.cy.js
        env:
          CYPRESS_RECORD_KEY: "chpt_47283b83342b338"  # Your Cypress Record Key
          CHROMATIC_ARCHIVE_LOCATION: "/home/runner/work/Aladia-Project/Aladia-Project/cypress/e2e/test.cy.js"

      # Now run Chromatic for visual regression tests
      - name: Run Chromatic with Cypress E2E Tests
        run: ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222 npx chromatic --cypress --project-token="chpt_47283b83342b338" --exit-zero-on-changes
        env:
          CYPRESS_RECORD_KEY: "chpt_47283b83342b338"
          CHROMATIC_ARCHIVE_LOCATION: "/home/runner/work/Aladia-Project/Aladia-Project/cypress/e2e/test.cy.js"
